config/routes.rb
Rails.application.routes.draw do
  get 'main/first'
  mount Commontator::Engine => '/commontator'
  get 'page/personal'
  get 'page/placeorder'
  get 'page/myorders'
  resources :dishes
  devise_for :users
  get 'home/index'
  get '/page/order'
  post '/page/order'
  get '/page/confirmation'
  post '/page/confirmation'
  get 'home/statuses'
  post 'home/statuses'
  get 'home/change'
  post 'home/change'



  root "home#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    elsif user.chef?
      can :read, Dish
      can :create, Dish
      can :update, Dish do |dish|
        dish.try(:user) == user
      end
      can :destroy, Dish do |dish|
        dish.try(:user) == user
      end
    else
      can :read, Dish
    end





  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
  has_many :orders, dependent: :destroy
  belongs_to :user
  acts_as_commontable
  mount_uploader :avatar, AvatarUploader
  validates :dish_name, :presence => :true
  validates :time_of_last_order, :presence => :true
  validates :maxOrder, :presence => :true
  validates :ready_by, :presence => :true
  validates :price, :presence => :true




end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :dish
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/status.rb
class Status < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  acts_as_commontator
  belongs_to :role
  belongs_to :status
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :registerable, :lockable

  before_save :assign_status
  def assign_status
    self.status = Status.find_by("status_name = ?",'Available') if self.status.nil?

  end
  def admin?
    self.role.name == "Admin" if !self.role.blank?
  end
  def chef?
    self.role.name == "Chef" if !self.role.blank?
  end
  def customer?
    self.role.name == "Customer" if !self.role.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :update_sanitized_params, if: :devise_controller?
  before_filter :set_timezone

  def update_sanitized_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role_id, :email, :password,:name,:address])
  end

  def set_timezone
    Time.zone = 'Kolkata'
  end

end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]
  # GET /dishes
  # GET /dishes.json



  def index
    @dishes = Dish.all
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
  end
  def hello

  end
  def personal
  if user_signed_in?
  @dishes=Dish.where('user = ?',current_user)
    end
  end
  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  # POST /dishes.json
  def create

    @dish = Dish.new(dish_params)
    @dish.user=current_user
    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    @dish.user=current_user
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_url, notice: 'Dish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.require(:dish).permit(:user_id, :dish_name, :time_of_last_order, :maxOrder, :price, :ready_by, :avatar)
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if user_signed_in?
    @chef = User.find_by_email(current_user.email)
    @orders=Order.where(dish_id: Dish.where("user_id = ?",current_user).select(:id) )

    end

  end

  def change
    user = User.find(current_user.id)
    puts params[:role]
    puts user.name
    user.update_attribute :role_id, params[:role]
    puts user.errors.details
    redirect_to home_index_path


  end



  def statuses

    user = User.find(current_user.id)
    puts params[:status]
    puts user.name
    user.update_attribute :status_id, params[:status]
    puts user.errors.details
    redirect_to home_index_path

  end

  end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def first
    render :layout => false
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController


  def personal

      @dishes=Dish.where('user_id = ?',current_user)


  end

  def placeorder
    @dishes=Dish.where('(time_of_last_order >= ?) AND ("maxOrder" > ?) AND user_id != ?',  Time.zone.now(), 0,current_user)
  end
  def order

    puts params[:order].inspect
    @found = params['order'].map(&:to_i)
    session[:dishes_wanted] = @found
    @dishes=Dish.where("id IN (?)",@found)

  end
  def confirmation
    #puts params[:dish].inspect
    @quantity=params[:quantity].map(&:to_i)
    @list=0
    #puts @quantity

    for k in session[:dishes_wanted]
      @dishid=Dish.find(k)
      order=Order.new

      order.dish= @dishid

      order.quantity=@quantity[@list]
      @list=@list+1

      order.user=current_user

      order.save

      @newdish=Dish.find(@dishid)

      @newdish.maxOrder=@newdish.maxOrder-order.quantity
      @newdish.save
    end
  end
  def myorders

    #@dishes=Dish.where(id: Order.where("user_id = ?",current_user).select(:dish_id) )
    #@chef=User.where(id: Order.where("user_id = ?",current_user).select(:user_id) )
    @orders=Order.where("user_id = ?",current_user)


  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/dishes/edit.html.erb
<h1>Editing Dish</h1>

<%= render 'form', dish: @dish %>

<%= link_to 'Show', @dish %> |
<%= link_to 'Back', dishes_path %>

app/views/dishes/hello.html.erb
Hello Ranjith

app/views/dishes/index.html.erb
<!DOCTYPE html>

<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=devidev-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AIT Homechefs</title>

  <!-- [ FONT-AWESOME ICON ]
        =========================================================================================================================-->
  <link rel="stylesheet" type="text/css" href="library/font-awesome-4.3.0/css/font-awesome.min.css">

  <!-- [ PLUGIN STYLESHEET ]
        =========================================================================================================================-->
  <link rel="shortcut icon" type="image/x-icon" href="images/icon.png">
  <link rel="stylesheet" type="text/css" href="css/animate.css">
  <link rel="stylesheet" type="text/css" href="css/owl.carousel.css">
  <link rel="stylesheet" type="text/css" href="css/owl.theme.css">
  <link rel="stylesheet" type="text/css" href="css/magnific-popup.css">

  <!-- TABLE CSS ==========================-->
  <%= stylesheet_link_tag "table" %>
  <!-- [ Boot STYLESHEET ]
        =========================================================================================================================-->
  <link rel="stylesheet" type="text/css" href="library/bootstrap/css/bootstrap-theme.min.css">
  <link rel="stylesheet" type="text/css" href="library/bootstrap/css/bootstrap.css">
  <!-- [ DEFAULT STYLESHEET ]
  =========================================================================================================================-->
  <link rel="stylesheet" type="text/css" href="css/style.css">
  <link rel="stylesheet" type="text/css" href="css/responsive.css">
  <link rel="stylesheet" type="text/css" href="css/color/rose.css">

</head>
<body style="background-image: url('https://d3ui957tjb5bqd.cloudfront.net/images/screenshots/products/10/106/106397/kbbn6c8xv6vshiuzkff7gz4t38b9lm42hbbbz66awuav5lonsvlciqfgixucmzbw-f.jpg?1399222055'); background-repeat: no-repeat; background-size: cover; margin-left: 3cm;" >
<!-- [ LOADERs ]
================================================================================================================================-->
<!--<div class="preloader">
  <div class="loader theme_background_color">
    <span></span>

  </div>
</div> -->
<!-- [ /PRELOADER ]
=============================================================================================================================-->
<!-- [WRAPPER ]
=============================================================================================================================-->
<div class="wrapper">
  <!-- [NAV]
 ============================================================================================================================-->
  <!-- Navigation
   ==========================================-->
  <nav  class=" nim-menu navbar navbar-default navbar-fixed-top">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <% if !user_signed_in?%>
            <a class="navbar-brand" href="index.html"><%= image_tag "/images/#AIT Homechefs.png" %></a>
        <% end%>
        <% if user_signed_in?%>
            <% if current_user.role.name=="Chef" %>
                <a class="navbar-brand" href="index.html"><%= image_tag "/images/#IamCooking.png" %></a>
            <% else if current_user.role.name=="Customer" %>
                    <a class="navbar-brand" href="index.html"><%= image_tag "/images/#IamHungry.png" %></a>
                <% end%>
            <% end%>
        <% end %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#" class="page-scroll">About </a></li>
          <li><a href="#" class="page-scroll">Contact us</a></li>
          <% if user_signed_in?%>
              <% if current_user.role.name=="Customer" %>
                  <li><a href="/home/index" class="page-scroll">Home</a></li>
                  <li><a href="/page/placeorder" class="page-scroll">Place Order</a></li>
                  <li><a href="/page/myorders" class="page-scroll">My Orders</a></li>
                  <li><p id="notice" class="page-scroll"><%= notice %></p></li>

                  <li><a class="page-scroll" style="color: white">Welcome <%= current_user.email %>! Not you?</a></li>
                  <li><a href="/users/sign_out" class="page-scroll">Sign Out</a></li>
              <% end %>
          <% end %>
          <!-- CHEF =========================================================================================================== -->
          <% if user_signed_in?%>
              <% if current_user.role.name=="Chef" %>
                  <li><a href="/home/index" class="page-scroll">Home</a></li>
                  <li><a href="/page/personal" class="page-scroll">View Your Menu</a></li>
                  <li><a href="/dishes/new" class="page-scroll">Cooking New Dish?</a></li>
                  <li><a class="page-scroll" style="color: white">Welcome <%= current_user.email %>! Not you?</a></li>
                  <li><a href="/users/sign_out" class="page-scroll">Sign Out</a></li>
              <% end %>
          <% end %>

        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>


  <!-- [/NAV]
============================================================================================================================-->





</div>


<!-- [ /WRAPPER ]
=============================================================================================================================-->

<!-- [ DEFAULT SCRIPT ] -->

<%= javascript_include_tag "modernizr.custom.97074.js"%>
<%= javascript_include_tag "bootstrap.js"%>
<%= javascript_include_tag "jquery.easing.1.3.js"%>
<%= javascript_include_tag "vegas.min.js"%>
<%= javascript_include_tag "plugins.js"%>
<%= javascript_include_tag "typed.js"%>
<%= javascript_include_tag "fappear.js"%>
<%= javascript_include_tag "jquery.countTo.js"%>
<%= javascript_include_tag "owl.carousel.js"%>
<%= javascript_include_tag "jquery.magnific-popup.min.js"%>
<%= javascript_include_tag "SmoothScroll.js"%>
<%= javascript_include_tag "common.js"%>


<!-- BODY========================================================================= -->

<br/><br/>
  <p id="notice"><%= notice %></p>


  <table style="background: -webkit-linear-gradient(left, #25c481, #25b7c4);
      background: linear-gradient(to right, #25c481, #25b7c4);">
    <thead>
    <th colspan="8"><h2 >Dishes</h2 ></th>
    <tr>
      <th>User</th>
      <th>Dish name</th>
      <th colspan="2">Timeoflastorder</th>
      <th>Maxorder</th>
      <th>Ready by</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @dishes.each do |dish| %>
        <tr>
          <td><%= dish.user.name %></td>
          <td><%= dish.dish_name %></td>
          <td colspan="2"><%= dish.time_of_last_order.strftime("%H:%M:%S") %></td>
          <td><%= dish.maxOrder %></td>
          <td><%= dish.ready_by.strftime("%H:%M:%S") %></td>
          <td><%= dish.price %></td>
          <td><%= link_to 'Show', dish %></td>
          <td><%= link_to 'Edit', edit_dish_path(dish) %></td>
          <td><%= link_to 'Destroy', dish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>

<!-- [FOOTER]
     ============================================================================================================================-->
<br/><br/><br/>
<footer class="site-footer section-spacing text-center " id="eight">

  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <p class="footer-links"><a href="#">Terms of Use</a> <a href="#">Privacy Policy</a></p>
      </div>
      <div class="col-md-4"> <small>&copy; 2015 Kiriti Velivela & Ranjith Dontamsetti. All rights reserved.</small></div>
      <div class="col-md-4">

      </div>
    </div>
  </div>
</footer>



<!-- [/FOOTER]
============================================================================================================================-->


</body>

</html>

app/views/dishes/new.html.erb
<%= render 'form', dish: @dish %>

app/views/dishes/personal.html.erb
<p id="notice"><%= notice %></p>

<h1>Dishes</h1>

<table>
  <thead>
  <tr>
    <th>User</th>
    <th>Dish name</th>
    <th colspan="2">Timeoflastorder</th>
    <th>Maxorder</th>
    <th>Ready by</th>
    <th>Price</th>
    <th colspan="2">Image</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @dishes.each do |dish| %>
      <tr>
        <td><%= dish.user.name %></td>
        <td><%= dish.dish_name %></td>
        <td colspan="2"><%= dish.time_of_last_order %></td>
        <td><%= dish.maxOrder %></td>
        <td><%= dish.Ready_by %></td>
        <td><%= dish.price %></td>
        <td colspan="2"><%= image_tag dish.avatar_url.to_s, height: 150, width: 150 %></td>
        <td><%= link_to 'Show', dish %></td>
        <td><%= link_to 'Edit', edit_dish_path(dish) %></td>
        <td><%= link_to 'Destroy', dish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dish', new_dish_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homechefs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <% if flash[:error] %>
      <div id="error">
        <%= flash[:error] %>
      </div>
  <% end %>
  <div id="container">
    <div id="user_status">
      <% if user_signed_in? %>
          Welcome <%= current_user.email %>! Not you?
          <%= link_to "Sign out", destroy_user_session_path, method: :get %>
      <% else %>
          <%= link_to "Sign up", new_user_registration_path %> or
          <%= link_to "Sign in", new_user_session_path %>.
      <% end %>
    </div>
    <%= yield %>
  </div>
  </body>
</html>

app/views/main/first.html.erb
<h1>Problem Set 5</h1>
<%= link_to "Project", home_index_path %>
<a href="/ps5.pdf" >Documentation </a>

app/views/page/personal.html.erb
<!DOCTYPE html>

<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=devidev-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AIT Homechefs</title>

  <!-- [ FONT-AWESOME ICON ]
        =========================================================================================================================-->
  <link rel="stylesheet" type="text/css" href="library/font-awesome-4.3.0/css/font-awesome.min.css">

  <!-- [ PLUGIN STYLESHEET ]
        =========================================================================================================================-->
  <link rel="shortcut icon" type="image/x-icon" href="images/icon.png">
  <link rel="stylesheet" type="text/css" href="css/animate.css">
  <link rel="stylesheet" type="text/css" href="css/owl.carousel.css">
  <link rel="stylesheet" type="text/css" href="css/owl.theme.css">
  <link rel="stylesheet" type="text/css" href="css/magnific-popup.css">

  <!-- TABLE CSS ==========================-->
  <%= stylesheet_link_tag "table" %>
  <!-- [ Boot STYLESHEET ]
        =========================================================================================================================-->
  <link rel="stylesheet" type="text/css" href="library/bootstrap/css/bootstrap-theme.min.css">
  <link rel="stylesheet" type="text/css" href="library/bootstrap/css/bootstrap.css">
  <!-- [ DEFAULT STYLESHEET ]
  =========================================================================================================================-->
  <link rel="stylesheet" type="text/css" href="css/style.css">
  <link rel="stylesheet" type="text/css" href="css/responsive.css">
  <link rel="stylesheet" type="text/css" href="css/color/rose.css">

</head>
<body style="background-image: url('https://d3ui957tjb5bqd.cloudfront.net/images/screenshots/products/10/106/106397/kbbn6c8xv6vshiuzkff7gz4t38b9lm42hbbbz66awuav5lonsvlciqfgixucmzbw-f.jpg?1399222055'); background-repeat: no-repeat; background-size: cover; margin-left: 3cm; opacity: 1000" >
<!-- [ LOADERs ]
================================================================================================================================-->
<!--<div class="preloader">
  <div class="loader theme_background_color">
    <span></span>

  </div>
</div> -->
<!-- [ /PRELOADER ]
=============================================================================================================================-->
<!-- [WRAPPER ]
=============================================================================================================================-->
<div class="wrapper">
  <!-- [NAV]
 ============================================================================================================================-->
  <!-- Navigation
   ==========================================-->
  <nav  class=" nim-menu navbar navbar-default navbar-fixed-top">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <% if !user_signed_in?%>
            <a class="navbar-brand" href="index.html"><%= image_tag "/images/#AIT Homechefs.png" %></a>
        <% end%>
        <% if user_signed_in?%>
            <% if current_user.role.name=="Chef" %>
                <a class="navbar-brand" href="index.html"><%= image_tag "/images/#IamCooking.png" %></a>
            <% else if current_user.role.name=="Customer" %>
                    <a class="navbar-brand" href="index.html"><%= image_tag "/images/#IamHungry.png" %></a>
                <% end%>
            <% end%>
        <% end %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#" class="page-scroll">About </a></li>
          <li><a href="#" class="page-scroll">Contact us</a></li>
          <% if user_signed_in?%>
              <% if current_user.role.name=="Customer" %>
                  <li><a href="/home/index" class="page-scroll">Home</a></li>
                  <li><a href="/page/placeorder" class="page-scroll">Place Order</a></li>
                  <li><a href="/page/myorders" class="page-scroll">My Orders</a></li>
                  <li><p id="notice" class="page-scroll"><%= notice %></p></li>

                  <li><a class="page-scroll" style="color: white">Welcome <%= current_user.email %>! Not you?</a></li>
                  <li><a href="/users/sign_out" class="page-scroll">Sign Out</a></li>
              <% end %>
          <% end %>
          <!-- CHEF =========================================================================================================== -->
          <% if user_signed_in?%>
              <% if current_user.role.name=="Chef" %>
                  <li><a href="/home/index" class="page-scroll">Home</a></li>
                  <li><a href="/page/personal" class="page-scroll">View Your Menu</a></li>
                  <li><a href="/dishes/new" class="page-scroll">Cooking New Dish?</a></li>
                  <li><a class="page-scroll" style="color: white">Welcome <%= current_user.email %>! Not you?</a></li>
                  <li><a href="/users/sign_out" class="page-scroll">Sign Out</a></li>
              <% end %>
          <% end %>

        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>


  <!-- [/NAV]
============================================================================================================================-->





      </div>


  <!-- [ /WRAPPER ]
  =============================================================================================================================-->

  <!-- [ DEFAULT SCRIPT ] -->

  <%= javascript_include_tag "modernizr.custom.97074.js"%>
  <%= javascript_include_tag "bootstrap.js"%>
  <%= javascript_include_tag "jquery.easing.1.3.js"%>
  <%= javascript_include_tag "vegas.min.js"%>
  <%= javascript_include_tag "plugins.js"%>
  <%= javascript_include_tag "typed.js"%>
  <%= javascript_include_tag "fappear.js"%>
  <%= javascript_include_tag "jquery.countTo.js"%>
  <%= javascript_include_tag "owl.carousel.js"%>
  <%= javascript_include_tag "jquery.magnific-popup.min.js"%>
  <%= javascript_include_tag "SmoothScroll.js"%>
  <%= javascript_include_tag "common.js"%>


  <!-- BODY========================================================================= -->
  <!-- CUSTOMER================================================================ -->
<p id="notice"><%= notice %></p>



<table style="background: -webkit-linear-gradient(left, #25c481, #25b7c4);
    background: linear-gradient(to right, #25c481, #25b7c4);">
  <thead>
  <th colspan="8"><h2 >Dishes</h2 ></th>
  <tr>
    <th>Chef</th>
    <th>Dish name</th>
    <th colspan="2">Timeoflastorder</th>
    <th>Maxorder</th>
    <th>Ready by</th>

    <th>Price</th>
    <th>Image</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @dishes.each do |dish| %>
      <tr>
        <td><%= dish.user.name %></td>
        <td><%= dish.dish_name %></td>
        <td colspan="2"><%= dish.time_of_last_order %></td>
        <td><%= dish.maxOrder %></td>
        <td><%= dish.ready_by %></td>
        <td><%= dish.price %></td>
        <td colspan="2"><%= image_tag dish.avatar_url.to_s, height: 150, width: 150,alt: 'No Image' %></td>
        <td><%= link_to 'Comment', dish %></td>
        <td><%= link_to 'Make Changes', edit_dish_path(dish) %></td>
        <td><%= link_to 'Remove', dish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>



<br/><br/>


<!-- [FOOTER]
     ============================================================================================================================-->
<br/><br/><br/>
<footer class="site-footer section-spacing text-center " id="eight">

  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <p class="footer-links"><a href="#">Terms of Use</a> <a href="#">Privacy Policy</a></p>
      </div>
      <div class="col-md-4"> <small>&copy; 2015 Kiriti Velivela & Ranjith Dontamsetti. All rights reserved.</small></div>
      <div class="col-md-4">


        <!--social end-->

      </div>
    </div>
  </div>
</footer>



<!-- [/FOOTER]
============================================================================================================================-->


  </body>

</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>